server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: myalias

spring:
  main:
    banner-mode: off
    lazy-initialization: true
  messages:
    basename: i18n/messages
    encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      pool-name: HikariPool
      connection-test-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.tool.hbm2ddl.SchemaExport: DEBUG

coin-demo:
  info:
    version-path: /api/version
    release-time: "@RELEASE_TIME@"
    release-version: "@version@"
  scheduling:
    enabled: true
    interval: 5000

  external:
    coin-desk:
      url: 'https://api.coindesk.com/v1/bpi/currentprice.json'
